name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /tmp/bazel-cache
          key: ${{ runner.os }}-bazelcache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-bazelcache-
      - name: Build and push image
        run: bazelisk build --disk_cache=/tmp/bazel-cache //:nut_exporter_image.tar
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: bazelisk run @com_github_google_go_containerregistry//cmd/crane:crane -- push --platform linux/amd64 $(bazelisk info bazel-bin)/nut_exporter_image.tar ghcr.io/${{ github.repository }}:${{ github.sha }}
